# Generated by Django 5.0.14 on 2026-07-10 15:18

import backend.apps.core.managers
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='última sincronización')),
            ],
            options={
                'verbose_name': 'estación',
                'verbose_name_plural': 'estaciones',
                'db_table': 'tb_station',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='apellido')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Solo lectura')], default='viewer', max_length=10, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acceso al admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creación')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='último ingreso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'tb_user',
                'ordering': ['email'],
            },
            managers=[
                ('objects', backend.apps.core.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.BigIntegerField(verbose_name='id en estación')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('started_at', models.DateTimeField(verbose_name='inicio')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='término')),
                ('auto', models.BooleanField(default=False, verbose_name='automático')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.station')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'db_table': 'tb_shift',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=100, verbose_name='nº empleado')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='nombre')),
                ('user_type', models.CharField(default='normal', max_length=20, verbose_name='tipo')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('authorized', models.BooleanField(default=True, verbose_name='autorizado')),
                ('person_id', models.CharField(blank=True, max_length=100, verbose_name='personId HikCentral')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='core.station')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'db_table': 'tb_person',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.BigIntegerField(verbose_name='id en estación')),
                ('shift_remote_id', models.BigIntegerField(blank=True, null=True, verbose_name='id turno en estación')),
                ('employee_no', models.CharField(max_length=100, verbose_name='nº empleado')),
                ('person_name', models.CharField(blank=True, max_length=200, verbose_name='nombre')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('verify_method', models.CharField(blank=True, max_length=50, verbose_name='método verificación')),
                ('card_no', models.CharField(blank=True, max_length=100, verbose_name='nº tarjeta')),
                ('event_time', models.DateTimeField(verbose_name='fecha/hora')),
                ('status', models.CharField(choices=[('Ok', 'Colación válida'), ('Duplicado', 'Duplicado en turno'), ('SinTurno', 'Fuera de turno'), ('NoAutorizado', 'No autorizado')], max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recibido')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.shift')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.station')),
            ],
            options={
                'verbose_name': 'marcación',
                'verbose_name_plural': 'marcaciones',
                'db_table': 'tb_access_event',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='StationAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.station', verbose_name='estación')),
            ],
            options={
                'verbose_name': 'API key de estación',
                'verbose_name_plural': 'API keys de estaciones',
                'db_table': 'tb_station_api_key',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['station', 'started_at'], name='tb_shift_station_627f0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('station', 'remote_id'), name='uq_shift_station_remote'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['station', 'employee_no'], name='tb_person_station_578901_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('station', 'employee_no'), name='uq_person_station_employee'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['station', 'event_time'], name='tb_access_e_station_b770d1_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['event_time'], name='tb_access_e_event_t_f7fb38_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['status'], name='tb_access_e_status_88ea64_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessevent',
            constraint=models.UniqueConstraint(fields=('station', 'remote_id'), name='uq_event_station_remote'),
        ),
    ]
