# Generated by Django 5.0.14 on 2026-08-17 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_station_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='detalle'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='is_visitor',
            field=models.BooleanField(default=False, verbose_name='visita'),
        ),
        migrations.AddField(
            model_name='station',
            name='config_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='configuración actualizada'),
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('start_min', models.PositiveSmallIntegerField(verbose_name='inicio (min desde 00:00)')),
                ('end_min', models.PositiveSmallIntegerField(verbose_name='término (min desde 00:00)')),
                ('enabled', models.BooleanField(default=True, verbose_name='habilitado')),
                ('all_companies', models.BooleanField(default=True, help_text='Apagado = solo las empresas autorizadas listadas; el resto queda NO AUTORIZADO.', verbose_name='todas las empresas')),
                ('allow_visitors', models.BooleanField(default=True, verbose_name='admite visitas (tarjeta RFID)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.station')),
            ],
            options={
                'verbose_name': 'turno programado',
                'verbose_name_plural': 'turnos programados',
                'db_table': 'tb_shift_schedule',
                'ordering': ['station', 'start_min', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftScheduleCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.shiftschedule')),
            ],
            options={
                'verbose_name': 'empresa autorizada',
                'verbose_name_plural': 'empresas autorizadas',
                'db_table': 'tb_shift_schedule_company',
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='VisitorCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=100, verbose_name='nº tarjeta')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='etiqueta')),
                ('enabled', models.BooleanField(default=True, verbose_name='habilitada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creada')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_cards', to='core.station')),
            ],
            options={
                'verbose_name': 'tarjeta de visita',
                'verbose_name_plural': 'tarjetas de visita',
                'db_table': 'tb_visitor_card',
                'ordering': ['created_at', 'card_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='shiftschedulecompany',
            constraint=models.UniqueConstraint(fields=('schedule', 'company'), name='uq_schedule_company'),
        ),
        migrations.AddConstraint(
            model_name='visitorcard',
            constraint=models.UniqueConstraint(fields=('station', 'card_no'), name='uq_visitor_card_station'),
        ),
    ]
