# Generated by Django 5.0.14 on 2026-08-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visitor_cards_shift_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='days_mask',
            field=models.PositiveSmallIntegerField(default=127, verbose_name='días de la semana'),
        ),
    ]
