# Generated by Django 5.0.14 on 2026-08-24 16:09

import backend.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shiftschedule_days_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='photo',
            field=models.BinaryField(blank=True, null=True, verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='uid'),
        ),
        migrations.AddField(
            model_name='shift',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Cerrado por el operador'), ('reemplazado', 'Reemplazado por el turno siguiente'), ('expirado', 'Cerrado al vencer la prórroga'), ('interrumpido', 'Interrumpido (terminal caído)')], default='', max_length=20, verbose_name='motivo de término'),
        ),
        migrations.AddField(
            model_name='shift',
            name='reopened_from_uid',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='reapertura de'),
        ),
        migrations.AddField(
            model_name='shift',
            name='schedule_uid',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='uid del turno programado'),
        ),
        migrations.AddField(
            model_name='shift',
            name='service_date',
            field=models.DateField(blank=True, null=True, verbose_name='día de servicio'),
        ),
        migrations.AddField(
            model_name='shift',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='uid'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='uid',
            field=models.CharField(default=backend.apps.core.models.new_uid, max_length=40, verbose_name='uid'),
        ),
        migrations.AddField(
            model_name='station',
            name='shift_overtime_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='Si empieza el turno siguiente, el turno en curso se cierra de inmediato sin esperar esta prórroga.', verbose_name='prórroga de turno (minutos)'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['is_visitor', 'event_time'], name='tb_access_e_is_visi_867451_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['station', 'schedule_uid', 'service_date'], name='tb_shift_station_03e401_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessevent',
            constraint=models.UniqueConstraint(condition=models.Q(('uid__gt', '')), fields=('station', 'uid'), name='uq_event_station_uid'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('uid__gt', '')), fields=('station', 'uid'), name='uq_shift_station_uid'),
        ),
    ]
