# Generated by Django 5.0.14 on 2026-08-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_accessevent_photo_accessevent_uid_shift_end_reason_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accessevent',
            name='uq_event_station_remote',
        ),
        migrations.RemoveConstraint(
            model_name='shift',
            name='uq_shift_station_remote',
        ),
        migrations.AddConstraint(
            model_name='accessevent',
            constraint=models.UniqueConstraint(condition=models.Q(('uid', '')), fields=('station', 'remote_id'), name='uq_event_station_remote'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('uid', '')), fields=('station', 'remote_id'), name='uq_shift_station_remote'),
        ),
    ]
