# Generated by Django 5.0.14 on 2026-09-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_person_meal_policy_shiftschedule_is_lunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='manual_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='colaciones ingreso manual'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='manual_entry',
            field=models.BooleanField(default=False, help_text='Nadie marca en este turno: en el terminal la cocinera ingresa la cantidad de colaciones que deja preparadas. Nunca se abre solo por horario.', verbose_name='ingreso manual'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Cerrado por el operador'), ('reemplazado', 'Reemplazado por el turno siguiente'), ('expirado', 'Cerrado al vencer la prórroga'), ('interrumpido', 'Interrumpido (terminal caído)'), ('ingreso_manual', 'Ingreso manual de colaciones')], default='', max_length=20, verbose_name='motivo de término'),
        ),
    ]
