# Generated by Django 5.0.14 on 2026-09-30 19:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ingreso_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=100, verbose_name='nº tarjeta')),
                ('card_label', models.CharField(blank=True, max_length=120, verbose_name='etiqueta de la tarjeta')),
                ('visitor_name', models.CharField(max_length=200, verbose_name='nombre de la visita')),
                ('visitor_document', models.CharField(blank=True, max_length=40, verbose_name='RUT / documento')),
                ('visitor_company', models.CharField(blank=True, max_length=200, verbose_name='empresa de procedencia')),
                ('host_company', models.CharField(blank=True, max_length=200, verbose_name='empresa visitada')),
                ('host_name', models.CharField(blank=True, max_length=200, verbose_name='funcionario visitado')),
                ('delivered_by_name', models.CharField(blank=True, max_length=200, verbose_name='entregada por')),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='entregada el')),
                ('returned_by_name', models.CharField(blank=True, max_length=200, verbose_name='recibida por')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='devuelta el')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='observación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_delivered', to=settings.AUTH_USER_MODEL)),
                ('host_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visits', to='core.person')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_returned', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.station')),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visitas',
                'db_table': 'tb_visit',
                'ordering': ['-delivered_at'],
                'indexes': [models.Index(fields=['station', 'card_no', 'delivered_at'], name='tb_visit_station_8328c5_idx'), models.Index(fields=['delivered_at'], name='tb_visit_deliver_026439_idx')],
            },
        ),
    ]
