# Generated by Django 5.0.14 on 2026-10-01 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_role_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_hash',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='hash de la foto'),
        ),
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField(verbose_name='foto')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='core.person')),
            ],
            options={
                'verbose_name': 'foto de persona',
                'verbose_name_plural': 'fotos de personas',
                'db_table': 'tb_person_photo',
            },
        ),
    ]
