# Generated by Django 5.0.14 on 2026-10-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='persons_refresh_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='actualización de personas solicitada'),
        ),
        migrations.AddField(
            model_name='station',
            name='persons_refreshed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='personas leídas de HikCentral'),
        ),
    ]
