# Generated by Django 5.0.14 on 2026-10-01 18:10

import backend.apps.core.models
from django.db import migrations, models


def unique_uids(apps, schema_editor):
    """AddField pone el MISMO uid por defecto a todas las visitas existentes: se individualiza."""
    Visit = apps.get_model('core', 'Visit')
    for visit in Visit.objects.all().only('pk'):
        Visit.objects.filter(pk=visit.pk).update(uid=backend.apps.core.models.new_uid())


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_station_persons_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='meal_date',
            field=models.DateField(blank=True, null=True, verbose_name='día de la colación'),
        ),
        migrations.AddField(
            model_name='visit',
            name='meal_schedule_uid',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='uid del turno autorizado'),
        ),
        migrations.AddField(
            model_name='visit',
            name='meal_shift_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='turno autorizado'),
        ),
        migrations.AddField(
            model_name='visit',
            name='origin',
            field=models.CharField(default='backoffice', max_length=20, verbose_name='origen'),
        ),
        migrations.AddField(
            model_name='visit',
            name='uid',
            field=models.CharField(db_index=True, default=backend.apps.core.models.new_uid, max_length=40, verbose_name='uid'),
        ),
        migrations.AddField(
            model_name='visit',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='utilizada el'),
        ),
        migrations.AddField(
            model_name='visit',
            name='used_shift_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='turno en que se utilizó'),
        ),
        migrations.RunPython(unique_uids, migrations.RunPython.noop),
    ]
