# Generated by Django 5.0.14 on 2026-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_shifts_capability'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='test_mode',
            field=models.BooleanField(default=False, verbose_name='modo de pruebas'),
        ),
    ]
