# Generated by Django 5.0.14 on 2026-10-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_station_test_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='last_ip',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='dirección IP'),
        ),
    ]
