# Generated by Django 5.0.14 on 2026-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_station_last_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='auto_shifts',
            field=models.BooleanField(default=False, verbose_name='inicio y cierre automático de turnos'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Cerrado por el operador'), ('reemplazado', 'Reemplazado por el turno siguiente'), ('expirado', 'Cerrado al vencer la prórroga'), ('horario', 'Cerrado al terminar su horario'), ('interrumpido', 'Interrumpido (terminal caído)'), ('ingreso_manual', 'Ingreso manual de colaciones')], default='', max_length=20, verbose_name='motivo de término'),
        ),
    ]
