# Generated by Django 5.0.14 on 2026-10-08 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_station_auto_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='annul_reason',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='motivo de la anulación'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='annulled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anulada el'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='annulled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annulled_events', to=settings.AUTH_USER_MODEL, verbose_name='anulada por'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='annulled_by_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='anulada por'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_events', to=settings.AUTH_USER_MODEL, verbose_name='registrada por'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='entered_by_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='registrada por'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='entry_reason',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='motivo del ingreso manual'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='origin',
            field=models.CharField(choices=[('terminal', 'Terminal'), ('backoffice', 'Ingreso manual (backoffice)')], default='terminal', max_length=12, verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='accessevent',
            name='status',
            field=models.CharField(choices=[('Ok', 'Colación válida'), ('Duplicado', 'Duplicado en turno'), ('SinTurno', 'Fuera de turno'), ('NoAutorizado', 'No autorizado'), ('Anulado', 'Anulado')], max_length=20, verbose_name='estado'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha y hora')),
                ('category', models.CharField(db_index=True, max_length=20, verbose_name='categoría')),
                ('action', models.CharField(max_length=60, verbose_name='acción')),
                ('level', models.CharField(choices=[('info', 'Información'), ('warning', 'Atención'), ('error', 'Error')], default='info', max_length=10, verbose_name='nivel')),
                ('summary', models.CharField(max_length=400, verbose_name='resumen')),
                ('station_name', models.CharField(blank=True, default='', max_length=120, verbose_name='estación')),
                ('user_name', models.CharField(blank=True, default='', max_length=200, verbose_name='usuario')),
                ('ip', models.CharField(blank=True, default='', max_length=45, verbose_name='IP')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='detalle')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='core.accessevent')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='core.shift')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='core.station')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrada de bitácora',
                'verbose_name_plural': 'bitácora',
                'db_table': 'tb_audit_log',
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['category', 'at'], name='tb_audit_lo_categor_7b48df_idx'), models.Index(fields=['station', 'at'], name='tb_audit_lo_station_6e2579_idx')],
            },
        ),
    ]
