# Generated by Django 5.0.14 on 2026-10-05 16:54

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0021_station_auto_shifts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='servidor SMTP')),
                ('port', models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='puerto')),
                ('security', models.CharField(choices=[('starttls', 'STARTTLS (normalmente puerto 587)'), ('ssl', 'SSL/TLS (normalmente puerto 465)'), ('none', 'Sin cifrado (normalmente puerto 25)')], default='starttls', max_length=10, verbose_name='cifrado')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='usuario')),
                ('password_encrypted', models.TextField(blank=True, default='', verbose_name='contraseña (cifrada)')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='correo del remitente')),
                ('from_name', models.CharField(blank=True, default='Casino Backoffice', max_length=120, verbose_name='nombre del remitente')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('scheduler_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='programador visto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'servidor de correo',
                'verbose_name_plural': 'servidor de correo',
                'db_table': 'tb_mail_settings',
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('frequency', models.CharField(choices=[('daily', 'Todos los días'), ('weekly', 'Semanal (días de la semana)'), ('monthly', 'Mensual (un día del mes)')], default='weekly', max_length=10, verbose_name='frecuencia')),
                ('weekdays_mask', models.PositiveSmallIntegerField(default=1, verbose_name='días de la semana')),
                ('month_day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='día del mes')),
                ('send_time', models.TimeField(default=datetime.time(8, 0), verbose_name='hora de envío')),
                ('period', models.CharField(choices=[('previous_day', 'Día anterior'), ('same_day', 'Mismo día del envío'), ('previous_week', 'Semana anterior (lunes a domingo)'), ('previous_month', 'Mes anterior completo'), ('since_last', 'Desde el envío anterior hasta el día antes del envío'), ('last_days', 'Últimos N días (hasta el día anterior)')], default='previous_week', max_length=20, verbose_name='período del informe')),
                ('period_days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(366)], verbose_name='cantidad de días')),
                ('shift_name', models.CharField(blank=True, max_length=120, verbose_name='turno')),
                ('attach_excel', models.BooleanField(default=False, verbose_name='adjuntar también en Excel')),
                ('recipients', models.TextField(verbose_name='destinatarios')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='asunto')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='próximo envío')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_reports', to='core.station', verbose_name='estación')),
            ],
            options={
                'verbose_name': 'envío programado',
                'verbose_name_plural': 'envíos programados',
                'db_table': 'tb_scheduled_report',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=120, verbose_name='envío')),
                ('trigger', models.CharField(choices=[('schedule', 'Programado'), ('manual', 'Manual')], default='schedule', max_length=10, verbose_name='origen')),
                ('scheduled_for', models.DateTimeField(verbose_name='programado para')),
                ('date_from', models.DateField(verbose_name='desde')),
                ('date_to', models.DateField(verbose_name='hasta')),
                ('recipients', models.TextField(verbose_name='destinatarios')),
                ('status', models.CharField(choices=[('pending', 'En cola'), ('sent', 'Enviado'), ('failed', 'Falló')], default='pending', max_length=10, verbose_name='estado')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='próximo intento')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='pedido por')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='reports.scheduledreport', verbose_name='envío programado')),
            ],
            options={
                'verbose_name': 'envío de informe',
                'verbose_name_plural': 'envíos de informes',
                'db_table': 'tb_report_delivery',
                'ordering': ['-scheduled_for', '-id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='tb_report_d_status_5a6947_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reportdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger', 'schedule')), fields=('report', 'scheduled_for'), name='uq_delivery_report_occurrence'),
        ),
    ]
